// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAutorestExample.ApiClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ExampleApplicationAPI.
    /// </summary>
    public static partial class ExampleApplicationAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static KendoMvcUIDataSourceResult ApiExampleGet(this IExampleApplicationAPI operations, object request = default(object))
            {
                return operations.ApiExampleGetAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<KendoMvcUIDataSourceResult> ApiExampleGetAsync(this IExampleApplicationAPI operations, object request = default(object), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExampleGetWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
