// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAutorestExample.ApiClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using WebAutorestExample.ApiClient;

    public partial class KendoMvcAggregateDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the KendoMvcAggregateDescriptor
        /// class.
        /// </summary>
        public KendoMvcAggregateDescriptor()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KendoMvcAggregateDescriptor
        /// class.
        /// </summary>
        public KendoMvcAggregateDescriptor(IList<KendoMvcAggregateFunction> aggregates = default(IList<KendoMvcAggregateFunction>), string member = default(string))
        {
            Aggregates = aggregates;
            Member = member;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aggregates")]
        public IList<KendoMvcAggregateFunction> Aggregates { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "member")]
        public string Member { get; set; }

    }
}
