// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebAutorestExample.ApiClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;
    using WebAutorestExample.ApiClient;

    public partial class KendoMvcAggregateFunction
    {
        /// <summary>
        /// Initializes a new instance of the KendoMvcAggregateFunction class.
        /// </summary>
        public KendoMvcAggregateFunction()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KendoMvcAggregateFunction class.
        /// </summary>
        public KendoMvcAggregateFunction(string aggregateMethodName = default(string), string caption = default(string), string sourceField = default(string), string functionName = default(string), string memberType = default(string), string resultFormatString = default(string))
        {
            AggregateMethodName = aggregateMethodName;
            Caption = caption;
            SourceField = sourceField;
            FunctionName = functionName;
            MemberType = memberType;
            ResultFormatString = resultFormatString;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aggregateMethodName")]
        public string AggregateMethodName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caption")]
        public string Caption { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceField")]
        public string SourceField { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "functionName")]
        public string FunctionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "memberType")]
        public string MemberType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resultFormatString")]
        public string ResultFormatString { get; set; }

    }
}
